const KEY='slatefolio-v01';
const VERSION='0.2.0';
const colors=['#35bff2','#9b7cff','#55d68b','#ffb84d','#ff6f91','#e8e95a','#c28cff','#7ed6df'];
let state=load(); let currentFolioId=state.currentFolioId||state.folios[0].id; let currentSectionId=null; let editingNoteId=null; let pendingImage=null; let selectedColor=colors[0];
const $=id=>document.getElementById(id); const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[c]));
function uid(p='id'){return p+'_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7)}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));if(x?.folios?.length)return x}catch(e){}const f={id:uid('folio'),name:'My Notebook',sections:[{id:uid('sec'),name:'Getting Started',color:colors[0],notes:[{id:uid('note'),title:'Welcome to SlateFolio',body:'<p>This is your first page. Create sections for different parts of your life, then add notes, sketches, photos, and ideas.</p><p><b>Tip:</b> Everything in this first build is saved locally in your browser.</p>',tags:['welcome'],created:Date.now(),updated:Date.now(),image:null}]}]};return{folios:[f],currentFolioId:f.id,inbox:[]}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));renderSidebar();updateInbox()}
function currentFolio(){return state.folios.find(f=>f.id===currentFolioId)||state.folios[0]}
function allNotes(){return state.folios.flatMap(f=>f.sections.flatMap(s=>s.notes.map(n=>({...n,folio:f,section:s}))));}
function toast(t){const el=$('toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function renderSidebar(){const list=$('folioList');list.innerHTML='';state.folios.forEach(f=>{const b=document.createElement('button');b.className='folio-item'+(f.id===currentFolioId?' active':'');b.innerHTML=`<i class="folio-dot"></i><span>${esc(f.name)}</span>`;b.onclick=()=>{currentFolioId=f.id;currentSectionId=null;save();showFolio()};list.appendChild(b)});showFolioListSections()}
function showFolioListSections(){/* reserved for future nested sidebar */}
function showFolio(){const f=currentFolio();$('crumbs').textContent=f.name; $('welcome').classList.toggle('hidden',!!currentSectionId);$('workspace').classList.toggle('hidden',!currentSectionId);$('searchView').classList.add('hidden'); if(currentSectionId){const s=f.sections.find(x=>x.id===currentSectionId);if(!s){currentSectionId=null;return showFolio()}$('crumbs').textContent=f.name+'  /  '+s.name;$('sectionTitle').textContent=s.name;renderNotes(s)}}
function renderNotes(s){const grid=$('notesGrid'),empty=$('emptyNotes');grid.innerHTML='';s.notes.slice().sort((a,b)=>b.updated-a.updated).forEach(n=>{const d=document.createElement('article');d.className='note-card';d.style.setProperty('--note-color',s.color);const text=(n.body||'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();d.innerHTML=`<h3>${esc(n.title||'Untitled note')}</h3><div class="note-preview">${esc(text||'Blank note')}</div><div class="note-foot"><span>${new Date(n.updated).toLocaleDateString()}</span><span>${n.tags?.length?'# '+esc(n.tags[0]):''}</span></div>`;d.onclick=()=>openNote(n.id);grid.appendChild(d)});empty.classList.toggle('hidden',s.notes.length>0)}
function openModal(id){$(id).classList.remove('hidden')}function closeModals(){document.querySelectorAll('.modal').forEach(m=>m.classList.add('hidden'))}
function openNote(noteId=null){editingNoteId=noteId;pendingImage=null;const f=currentFolio();const s=currentSectionId?f.sections.find(x=>x.id===currentSectionId):f.sections[0];const n=noteId?s.notes.find(x=>x.id===noteId):null;$('noteModalTitle').textContent=n?'Edit Note':'New Note';$('noteTitle').value=n?.title||'';$('noteBody').innerHTML=n?.body||'';$('noteTags').value=(n?.tags||[]).join(', ');populateNoteSections(n?.sectionId||s.id);$('deleteNoteBtn').style.visibility=n?'visible':'hidden';$('attachmentPreview').innerHTML=n?.image?`<img src="${n.image}" alt="Attached image">`:'';openModal('noteModal');setTimeout(()=>$('noteTitle').focus(),50)}
function populateNoteSections(selected){const sel=$('noteSection');sel.innerHTML='';currentFolio().sections.forEach(s=>{const o=document.createElement('option');o.value=s.id;o.textContent=s.name;o.selected=s.id===selected;sel.appendChild(o)})}
function saveNote(){const title=$('noteTitle').value.trim()||'Untitled note';const body=$('noteBody').innerHTML.trim();const tags=$('noteTags').value.split(',').map(x=>x.trim()).filter(Boolean).slice(0,15);const sid=$('noteSection').value;const f=currentFolio();let target=f.sections.find(s=>s.id===sid);if(!target)return;if(editingNoteId){for(const s of f.sections){const idx=s.notes.findIndex(n=>n.id===editingNoteId);if(idx>-1){const old=s.notes.splice(idx,1)[0];target.notes.push({...old,title,body,tags,updated:Date.now(),image:pendingImage??old.image,sectionId:sid});break}}}else target.notes.push({id:uid('note'),title,body,tags,created:Date.now(),updated:Date.now(),image:pendingImage,sectionId:sid});save();closeModals();currentSectionId=sid;showFolio();toast('Note saved')}
function deleteNote(){if(!editingNoteId)return;const f=currentFolio();for(const s of f.sections){const i=s.notes.findIndex(n=>n.id===editingNoteId);if(i>-1){s.notes.splice(i,1);break}}save();closeModals();showFolio();toast('Note deleted')}
function createSection(){const name=$('sectionName').value.trim();if(!name)return;const f=currentFolio();const s={id:uid('sec'),name,color:selectedColor,notes:[]};f.sections.push(s);save();$('sectionName').value='';closeModals();currentSectionId=s.id;showFolio();toast('Section created')}
function createFolio(){const name=$('folioName').value.trim();if(!name)return;const f={id:uid('folio'),name,sections:[]};f.sections.push({id:uid('sec'),name:'General',color:colors[0],notes:[]});state.folios.push(f);currentFolioId=f.id;save();$('folioName').value='';closeModals();currentSectionId=null;showFolio();toast('Folio created')}
function showSearch(){ $('welcome').classList.add('hidden');$('workspace').classList.add('hidden');$('searchView').classList.remove('hidden');$('searchInput').value='';$('searchInput').focus();renderSearch('')}
function renderSearch(q){const results=$('searchResults');const query=q.toLowerCase().trim();const hits=allNotes().filter(n=>!query||[n.title,n.body,n.tags?.join(' '),n.section.name,n.folio.name].join(' ').toLowerCase().includes(query));results.innerHTML=hits.length?hits.map(n=>`<div class="search-result" data-id="${n.id}"><small>${esc(n.folio.name)} / ${esc(n.section.name)}</small><h3>${esc(n.title||'Untitled note')}</h3><div class="muted">${esc((n.body||'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').slice(0,180))}</div></div>`).join(''):`<div class="empty-state"><div class="empty-icon">⌕</div><h3>No matches</h3><p>Try a different word or tag.</p></div>`;results.querySelectorAll('.search-result').forEach(el=>el.onclick=()=>{const n=allNotes().find(x=>x.id===el.dataset.id);currentFolioId=n.folio.id;currentSectionId=n.section.id;showFolio();openNote(n.id);save()})}
function updateInbox(){$('inboxCount').textContent=state.inbox.length}
function exportBackup(){const blob=new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString(),app:'SlateFolio',version:VERSION},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`slatefolio-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);toast('Backup exported')}
function importBackup(file){const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x.folios?.length)throw Error();state=x;currentFolioId=state.folios[0].id;currentSectionId=null;save();closeModals();showFolio();toast('Backup restored')}catch(e){toast('That backup could not be read')}};r.readAsText(file)}
function printSection(){const s=currentSectionId?currentFolio().sections.find(x=>x.id===currentSectionId):null;if(!s){toast('Open a section first');return}const w=window.open('','_blank');w.document.write(`<html><head><title>${esc(s.name)} — SlateFolio</title><style>body{font-family:Arial,sans-serif;max-width:800px;margin:40px auto;color:#111}h1{border-bottom:2px solid ${s.color};padding-bottom:10px}.note{page-break-inside:avoid;border-bottom:1px solid #ddd;padding:18px 0}.date{font-size:12px;color:#777}</style></head><body><h1>${esc(s.name)}</h1>${s.notes.map(n=>`<div class="note"><h2>${esc(n.title)}</h2><div class="date">${new Date(n.updated).toLocaleString()}</div>${n.image?`<img src="${n.image}" style="max-width:100%;max-height:500px">`:''}${n.body}</div>`).join('')}</body></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),300)}
function setupCanvas(){const c=$('drawCanvas'),rect=c.getBoundingClientRect(),dpr=devicePixelRatio||1;c.width=rect.width*dpr;c.height=rect.height*dpr;const ctx=c.getContext('2d');ctx.scale(dpr,dpr);ctx.fillStyle='#f7f8fa';ctx.fillRect(0,0,rect.width,rect.height);ctx.strokeStyle='#111827';ctx.lineCap='round';let down=false;c.onpointerdown=e=>{down=true;ctx.beginPath();ctx.moveTo(e.offsetX,e.offsetY)};c.onpointerup=()=>down=false;c.onpointerleave=()=>down=false;c.onpointermove=e=>{if(!down)return;ctx.lineWidth=+$('penSize').value;ctx.lineTo(e.offsetX,e.offsetY);ctx.stroke()}}
function addDrawing(){const url=$('drawCanvas').toDataURL('image/png');pendingImage=url;$('attachmentPreview').innerHTML=`<img src="${url}" alt="Drawing">`;closeModals();openModal('noteModal');toast('Drawing added to note')}
function setImagePreview(src,label='Attached image'){ $('attachmentPreview').innerHTML=`<img src="${src}" alt="${label}">`; }
async function scanToText(){
  const input=$('imageInput');
  if(!pendingImage){ toast('Take or attach a photo first'); input.click(); return; }
  if(!window.Tesseract){ toast('OCR library is unavailable'); return; }
  const status=$('ocrStatus');
  status.textContent='Reading the page…';
  try{
    const result=await Tesseract.recognize(pendingImage,'eng',{logger:m=>{if(m.status==='recognizing text') status.textContent=`Reading the page… ${Math.round((m.progress||0)*100)}%`;}});
    const text=(result.data.text||'').trim();
    if(!text){ status.textContent='No readable text found. Try a clearer photo.'; toast('No text found'); return; }
    const editor=$('noteBody');
    const existing=editor.innerHTML.trim();
    const blocks=text.split(/\n{2,}/).map(x=>x.split('\n').map(y=>y.trim()).filter(Boolean).join(' ')).filter(Boolean);
    const html=blocks.map(x=>`<p>${esc(x)}</p>`).join('');
    editor.innerHTML=existing ? `${existing}${html}` : html;
    status.textContent='Text added to the note. You can edit it now.';
    toast('Scanned text added');
  }catch(err){ console.error(err); status.textContent='OCR failed. Try a sharper, better-lit photo.'; toast('Could not read that image'); }
}

$('menuBtn').onclick=()=>$('sidebar').classList.toggle('open');$('newFolioBtn').onclick=()=>openModal('folioModal');$('newSectionBtn').onclick=()=>{selectedColor=colors[0];renderColors();openModal('sectionModal')};$('welcomeNewSection').onclick=$('newSectionBtn').onclick;$('newNoteBtn').onclick=()=>openNote();$('welcomeNewNote').onclick=()=>openNote();$('emptyNewNote').onclick=()=>openNote();$('searchFocusBtn').onclick=showSearch;$('searchInput').oninput=e=>renderSearch(e.target.value);$('themeBtn').onclick=()=>{document.documentElement.classList.toggle('light');toast(document.documentElement.classList.contains('light')?'Light mode':'Dark mode')};$('saveNoteBtn').onclick=saveNote;$('deleteNoteBtn').onclick=()=>{if(confirm('Delete this note?'))deleteNote()};$('saveSectionBtn').onclick=createSection;$('saveFolioBtn').onclick=createFolio;$('backupBtn').onclick=()=>openModal('backupModal');$('exportBtn').onclick=exportBackup;$('importInput').onchange=e=>e.target.files[0]&&importBackup(e.target.files[0]);$('printBtn').onclick=printSection;$('aboutBtn').onclick=()=>openModal('aboutModal');$('attachImageBtn').onclick=()=>$('imageInput').click();$('cameraBtn').onclick=()=>$('imageInput').click();$('imageInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{pendingImage=r.result;setImagePreview(r.result,'Scanned or attached photo');$('ocrStatus').textContent='Photo ready. Tap Scan to Text to import its writing.';toast('Photo added')};r.readAsDataURL(f)};$('ocrBtn').onclick=scanToText;$('drawBtn').onclick=()=>{openModal('drawModal');setTimeout(setupCanvas,50)};$('clearCanvasBtn').onclick=setupCanvas;$('saveDrawingBtn').onclick=addDrawing;document.querySelectorAll('.close-modal').forEach(b=>b.onclick=closeModals);document.querySelectorAll('[data-cmd]').forEach(b=>b.onclick=()=>document.execCommand(b.dataset.cmd,false,null));$('inboxBtn').onclick=()=>toast('Inbox is ready for the next build');
function renderColors(){const r=$('colorRow');r.innerHTML='';colors.forEach(c=>{const b=document.createElement('button');b.className='color-swatch'+(c===selectedColor?' selected':'');b.style.background=c;b.onclick=()=>{selectedColor=c;renderColors()};r.appendChild(b)})}renderColors();renderSidebar();updateInbox();showFolio();
